"use client";

import "./globals.css";
import { useEffect } from "react";
import { Montserrat } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import { languageAtom } from "@/store";
import { useSetAtom } from "jotai";
import { useLocalStorage } from "@/lib/hooks/useLocalStorage";
import ThemeCSS from "./Theme.style";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Pazderski Projekt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const setLanguage = useSetAtom(languageAtom);

  const [lang] = useLocalStorage("lang", "en");

  useEffect(() => {
    setLanguage(lang);
  }, [setLanguage, lang]);

  return (
    <html lang="en">
      <ThemeCSS />
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
